### ISSUE TITLE
User's authcode to SMS

### ISSUE THREAD

**Issue by sungjius** [XrunMeta/IssueTracker#10]
<img width="512" alt="image" src="https://github.com/XrunMeta/IssueTracker/assets/81668851/40f2c9c1-1b54-4ca4-a5aa-6904072edc5c">

Alternative log-in available with SMS option. Not email auth.

**Comment by sungjius** [comment]
Try EMAIL AUTHCODE -> SMS authcode. (also you can found sms pages at source)

**Comment by bi-brilliant** [comment]
Thanks for feedback, anw we have change that function at this [repo](http://3.1.222.176/xrun/react-app.xrun/commit/ec5dc7643c2c73dc315adf432d185969ce7f43b9)
