### ISSUE TITLE
Region Bug in signup Page

### ISSUE THREAD

**Issue by opikropikin** [XrunMeta/IssueTracker#13]
There was a problem on the registration page, where the region column displayed location data even though the country region column had not been selected, but this problem has been resolved by simply changing several nodes in the blueprint

**Comment by sungjius** [comment]
> There was a problem on the registration page, where the region column displayed location data even though the country region column had not been selected, but this problem has been resolved by simply changing several nodes in the blueprint

Can I got some screenshot to solve this? After now, please attach images for helpful.

**Comment by opikropikin** [comment]
okey mr young,,,
