### ISSUE TITLE
Change labels text 

### ISSUE THREAD

**Issue by sungjius** [XrunMeta/IssueTracker#15]
<img width="457" alt="image" src="https://github.com/XrunMeta/IssueTracker/assets/81668851/e7897d25-1f11-418e-8dd6-126e8ef9c100">

in english 
There is [coin symbol] supported by [company]

in korean 
[company] 에서 제공하는 [coin symbol] 이 있습니다.

<img width="355" alt="image" src="https://github.com/XrunMeta/IssueTracker/assets/81668851/40b81d03-426f-4712-ae23-93294943107c">

in english 
You can catch [count] [symbol].

in korean
[count] 개의 잡을 수 있는 [symbol] 이 있습니다.

**Comment by bi-brilliant** [comment]
We have change as request and you can see [here](http://3.1.222.176/xrun/react-app.xrun/commit/0df6dafda95a5e579b9e465edf7dde8013eee911)
Thanks :)
