### ISSUE TITLE
Test LAB (Daily Report 03 Apr 2024)

### ISSUE THREAD

**Issue by opikropikin** [XrunMeta/IssueTracker#19]
Testing Samsung Testbed Samsung S24 Ultra Android 14 Gumi Korea Region - Working
- Testing Samsung Testbed Samsung S24 +  Android 14 Gumi Korea Region - Working
- Testing Samsung Testbed Samsung S23 Android 14 Gumi Korea Region - Working
- Testing Samsung Testbed Samsung S22 Android 13 Gumi Korea Region - Installing but never finished
- Testing Samsung Testbed Samsung S21 Android 14 Gumi Korea Region - Installing but never finished
![TESTLAB1](https://github.com/XrunMeta/IssueTracker/assets/123038142/74ab5d86-9875-4a57-8473-5824407882a8)
![TETLAB2](https://github.com/XrunMeta/IssueTracker/assets/123038142/1f454706-bb7f-424c-8840-9ea7f5a6ce70)

**Comment by vviusoo** [comment]
Please also check the login screen.

**Comment by opikropikin** [comment]
I tested it from the login, sginup, setting, and play the game

**Comment by vviusoo** [comment]
Please capture the login screen and upload it
