### ISSUE TITLE
Test LAB (Daily Report 04 April 2024)

### ISSUE THREAD

**Issue by opikropikin** [XrunMeta/IssueTracker#23]
Testing Samsung Testbed Samsung S23 Ultra Android 13 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S23 Ultra Android 14 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S23 + Android 13 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S23 + Android 14 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S22 Ultra Android 12 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S22 Ultra Android 13 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S22 Ultra Android 14 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S22 + Android 12 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S22 + Android 13 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S22 + Android 14 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S22 Android 12 Gumi Korea Region - Working
Testing Samsung Testbed Samsung S22 Android 13 Gumi Korea Region - Working
[REMOTE TEST LAB PART2.pptx](https://github.com/XrunMeta/IssueTracker/files/14863763/REMOTE.TEST.LAB.PART2.pptx)

**Comment by sungjius** [comment]
Could we test other region vietnam?
focus with S23~S24ultra. (latest)
