### ISSUE TITLE
QR code package select.

### ISSUE THREAD

**Issue by sungjius** [XrunMeta/IssueTracker#24]
You mean use this npm https://gitlab.com/luanluuhaui/react-native-barcode-z-xing#readme? Or previously npm, using this https://www.npmjs.com/package/react-native-qrcode-scanner?

_Originally posted by @mfebriann in https://github.com/XrunMeta/IssueTracker/issues/22#issuecomment-2038550713_

**Comment by mfebriann** [comment]
We will trying first to continue using zxing, if still not working we will revert and using latest npm

**Comment by sungjius** [comment]
Good 👍

**Comment by mfebriann** [comment]
This problem has been resolved http://3.1.222.176/xrun/react-app.xrun/commit/feb8d2ef4d848d4aa6fad564e9c8342743c4a7ef
