### ISSUE TITLE
xrun app testing

### ISSUE THREAD

**Issue by sungjius** [XrunMeta/IssueTracker#26]
Please test xrun react app with testbed. 

If any problem, report here. 

this issue estimate about 5days from today.

 I will spread coins at testing site. 👍 

### Testing devices 
- Galaxy A5x Series
- Galaxy S22 ~ latest

**Comment by mfebriann** [comment]
I found issues on devices:
- Samsung Galaxy S22+ Korea(Gumi) Android 14, Samsung Galaxy S22 Korea(Gumi) Android 14 - Download image qr code automatic force close
- Samsung Galaxy S20 Vietnam(Hanoi) Android 12, Samsung Galaxy S22+ Vietnam(Hanoi) Android 12 - 13, Samsung Galaxy S22 Vietnam(Hanoi) Android 13 - Coin AR can't show

**Comment by sungjius** [comment]
I will check with that device soon. Collect debug logs for debug.

**Comment by sungjius** [comment]
please post logs with zipped file with password. I will send password via other comm.

**Comment by mfebriann** [comment]
Okey mr young

**Comment by mfebriann** [comment]
Hello mr young, this logs https://github.com/XrunMeta/IssueTracker/issues/36#issuecomment-2044498026
