### ISSUE TITLE
Checking ClubX substain plannings

### ISSUE THREAD

**Issue by sungjius** [XrunMeta/IssueTracker#35]
As other apps, we must check newer playstore version every lunch app. 

Currently, firebase support Unity only, but we need to check version each time. 

If we could use firebase version checker, or not [use c++](https://firebase.google.com/docs/remote-config/get-started?platform=cpp&hl=id) way. I think c++ method is useful for our project. 

Also, as I knew, we had been handled, If yes, go next and close this issue. 

It may effort the close beta too.

**Comment by trisutrisnowapu** [comment]
Firebase is available in unreal engine plugin in marketplace assets like this one:
https://www.unrealengine.com/marketplace/en-US/product/firebase-goodies

![image](https://github.com/XrunMeta/IssueTracker/assets/14313339/4d046823-2875-4358-87c0-0ac1aa43f53d)

![image](https://github.com/XrunMeta/IssueTracker/assets/14313339/d0e54047-8db6-41d1-b060-997af92febdd)

**Comment by trisutrisnowapu** [comment]
It's on-sale now for $62.99 if you think we need to implement any of those features. But what and why would we implement any of the features?

**Comment by sungjius** [comment]
OK, @vviusoo will help you. Purchase confirmed.
