### ISSUE TITLE
Correction chart - clubx, app.

### ISSUE THREAD

**Issue by sungjius** [XrunMeta/IssueTracker#37]
Will publish clubx, app's correction chart. please note a chart and do bugs fix.

URL will send by other comm.

**Comment by trisutrisnowapu** [comment]
Yes Mr Yang we are aware of this issue, I have applied the fix, it was fixed but it happened again. I'm gonna need to debug it per node, will take some time. The quickest but manual fix are restarting the multiplayer server, @bi-brilliant has developed an API for restarting the unreal server, for temporary, we can restart the server by visiting this link and wait for 15 sec 

http://108.136.185.124:3000/restart

I think we will schedule a daily server restart while fixing the logic

**Comment by sungjius** [comment]
if could, try to leave LOG on server and client both? I think it's not only a onetime break, also I had. 

> Yes Mr Yang we are aware of this issue, I have applied the fix, it was fixed but it happened again. I'm gonna need to debug it per node, will take some time. The quickest but manual fix are restarting the multiplayer server, @bi-brilliant has developed an API for restarting the unreal server, for temporary, we can restart the server by visiting this link and wait for 15 sec
> 
> http://108.136.185.124:3000/restart
> 
> I think we will schedule a daily server restart while fixing the logic

**Comment by bi-brilliant** [comment]
> Will publish clubx, app's correction chart. please note a chart and do bugs fix.
> 
> URL will send by other comm.

Hello, I had update the result of device problem with some conclusions, you can check [here](https://github.com/XrunMeta/IssueTracker/issues/38)

**Comment by trisutrisnowapu** [comment]
> if could, try to leave LOG on server and client both? I think it's not only a onetime break, also I had.
> 
> > Yes Mr Yang we are aware of this issue, I have applied the fix, it was fixed but it happened again. I'm gonna need to debug it per node, will take some time. The quickest but manual fix are restarting the multiplayer server, @bi-brilliant has developed an API for restarting the unreal server, for temporary, we can restart the server by visiting this link and wait for 15 sec
> > http://108.136.185.124:3000/restart
> > I think we will schedule a daily server restart while fixing the logic

I'm not sure if distribution build can have the log also, but I will check

**Comment by bi-brilliant** [comment]
> if could, try to leave LOG on server and client both? I think it's not only a onetime break, also I had.


I had update for server restarter both manual & auto (every 00:00 is restart) who had log saver. You can check [here](https://github.com/XrunMeta/IssueTracker/issues/41)

**Comment by heewoo1986** [comment]
2Days My testing going well..! But Something unstable and just go out accidently

**Comment by trisutrisnowapu** [comment]
> 2Days My testing going well..! But Something unstable and just go out accidently

Can you please elaborate, did it randomly happened when playing in level? or when click Play and starting to connect to level?
