### ISSUE TITLE
Continue to testing, appstore version update

### ISSUE THREAD

**Issue by XrunMeta** [XrunMeta/IssueTracker#49]
as follow #31 

continue solve playstore issue and testing. update as new thread.

**Comment by heewoo1986** [comment]
If you followed the guidelines of Google Playstore, wouldn't it be uploaded 
?

**Comment by bi-brilliant** [comment]
> continue solve playstore issue and testing. update as new thread.

I asked again via email to Google service, then here is their response
![Googleplay Service response](https://github.com/XrunMeta/IssueTracker/assets/85775620/e64e8f6f-da0f-4c80-b7cd-23acf63425cd)

**Comment by trisutrisnowapu** [comment]
I try searching for any resources regarding the message but found nothing.. I don't understand, I wonder if it's related to new policy from google. It's very weird that we don't find any developer finding the same problem. Store version is incremented as usual (or it can not upload), I tried increment Store Version offset (arm64) and Store Version offset (x86_64) and Version Display Name (usually x.y) but still not success. It only happen when we upload to public testing, it never happened in any case before

**Comment by sungjius** [comment]
check this article [play-store-having-new-version](https://stackoverflow.com/questions/27020815/play-store-having-new-version-of-the-app-but-not-showing-update)

[play-store-does-not-push-new-versions-on-internal-testing-to-users](https://stackoverflow.com/questions/71112111/play-store-does-not-push-new-versions-on-internal-testing-to-users)

this would helpful for us?
I need time to gather other possible reason.

**Comment by trisutrisnowapu** [comment]
> check this article [play-store-having-new-version](https://stackoverflow.com/questions/27020815/play-store-having-new-version-of-the-app-but-not-showing-update)
> 
> [play-store-does-not-push-new-versions-on-internal-testing-to-users](https://stackoverflow.com/questions/71112111/play-store-does-not-push-new-versions-on-internal-testing-to-users)
> 
> this would helpful for us? I need time to gather other possible reason.

No Mr Young, this is not what happened with us here.

We experienced this almost everytime we push any update, when the upload is finished, we need to uninstall the older app, and restart the phone, after restart we download again. Only that way we can get the latest upload version. If we uninstall but not restart, we will download older app version. The phone must be restarted.

**Comment by bi-brilliant** [comment]
> continue solve playstore issue and testing. update as new thread.

We had good update about it, now our CLUBX Mobile is on public tester approved🙂

![Post overview CLUBX Playstore has published (Public Test)](https://github.com/XrunMeta/IssueTracker/assets/85775620/dbeb88da-9142-4f7e-bed4-f301d83f62b2)

![Post overview CLUBX Playstore](https://github.com/XrunMeta/IssueTracker/assets/85775620/8f634c5f-172d-4bc6-9ab4-6cc1d733ffc6)

![Post overview CLUBX Playstore has published (Public Test)(2)](https://github.com/XrunMeta/IssueTracker/assets/85775620/13f81d84-c062-4165-ae46-003f07eac49e)

**Comment by trisutrisnowapu** [comment]
Playstore Current status is now Public Testing.
https://play.google.com/store/apps/details?id=run.xrun.clubx

But if people search in playstore not every device will found the app, it will take some time to propagate worldwide. But it's available in developer's page.

**Comment by XrunMeta** [comment]
Good work. now we can announce open-beta-test now.
