### ISSUE TITLE
About disclosure date

### ISSUE THREAD

**Issue by heewoo1986** [XrunMeta/IssueTracker#50]
Its much better the graphs and the rest of the data to be static and consistent with Coinmarketcap in the website disclosure section. because Many new users and people are come and see
![스크린샷 2024-04-29 오후 2 17 41](https://github.com/XrunMeta/IssueTracker/assets/45555727/35d4779d-2751-45d3-acb7-fc7a1e9620d3)

**Comment by bi-brilliant** [comment]
> Its much better the graphs and the rest of the data to be static and consistent with Coinmarketcap in the website disclosure section. because Many new users and people are come and see ![스크린샷 2024-04-29 오후 2 17 41](https://private-user-images.githubusercontent.com/45555727/326335175-35d4779d-2751-45d3-acb7-fc7a1e9620d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NzEyNTksIm5iZiI6MTcxNDQ3MDk1OSwicGF0aCI6Ii80NTU1NTcyNy8zMjYzMzUxNzUtMzVkNDc3OWQtMjc1MS00NWQzLWFjYjctZmM3YTFlOTYyMGQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA5NTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMzIzODlhODQ4ZGJmYjUzYWFhMTQwYjczZWZjYTRlOTljOWYwNTA5ZWQxYjFjNmFkNTYwMTY3MDdlMmQwZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mZDWHqnXXBcm06qC56AUmYBhCu7IetAD_rbCKLwVn6c)

Im collaborate with @mfebriann are working on this issue🙂
![Chart CoinMarketCap with NodeJS](https://github.com/XrunMeta/IssueTracker/assets/85775620/299d2344-83ff-4e08-95ab-914f1ee0677d)

**Comment by bi-brilliant** [comment]
We have update bot for coinmarketcap data saver

![CMC Data Store - Bot server](https://github.com/XrunMeta/IssueTracker/assets/85775620/bf27c3a2-86d3-4fb4-a2a9-33e9101db5e8)
![Disclosure chart has update](https://github.com/XrunMeta/IssueTracker/assets/85775620/710207cb-59bd-4e44-99e8-52d297584d9d)
