### ISSUE TITLE
ECORUN Developer Policies Suspending by 2 days

### ISSUE THREAD

**Issue by bi-brilliant** [XrunMeta/IssueTracker#6]
Hello, I received an email regarding the suspension of the ECORUN application which, if not handled within 3 days, will be suspended.

I read the details and it turns out it was related to the invalid [member deletion page](https://ecorun.store/rmvMember.php), the file should be with the **ecorun** folder but now it can't be found. I don't have access to the ecorun server and we just need `rmvMember.php` to be placed there..can you guys help?
![ECORUN Data Security Developer Policies suspending](https://github.com/XrunMeta/IssueTracker/assets/85775620/2bb74f81-ac8f-4517-9bbe-ad71630757da)
![ECORUN Remove member page](https://github.com/XrunMeta/IssueTracker/assets/85775620/d234eb71-45d5-470c-86bf-27fbfff4f0b3)
![ECORUN Suspending detail](https://github.com/XrunMeta/IssueTracker/assets/85775620/4fc821cd-a269-4867-bfb5-f3e0f3ed6e85)

**Comment by sungjius** [comment]
It is better to make a new url with google form. I will make and return url here.

**Comment by sungjius** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSdVVeSXeKDRQoJM9WYt7x2Zihh9mzagFJbveACC_rmR7OpCVA/viewform

replace deletion request form.

**Comment by bi-brilliant** [comment]
I had update the developer regulations and now is under review, Thanks🙂
![Deleting account ECORUN](https://github.com/XrunMeta/IssueTracker/assets/85775620/e594ae1a-7488-4644-9a90-6588f3eb9447)
