### ISSUE TITLE
Testing on Samsung Remote Testbed

### ISSUE THREAD

**Issue by trisutrisnowapu** [XrunMeta/IssueTracker#7]
Here's my experience using Samsung Testbed

I don't think it's a good idea to use this for testing clubx, since it doesn't represent the quality of the game. Or maybe anyone would like to try it yourself, I will send updated build.

![image](https://github.com/XrunMeta/IssueTracker/assets/14313339/617f27f6-d19e-45cf-b54f-0b9aa5b016b1)
![image](https://github.com/XrunMeta/IssueTracker/assets/14313339/dc874666-f084-4359-b0ba-261b947f9c21)
![image](https://github.com/XrunMeta/IssueTracker/assets/14313339/35cbe1d8-6369-4850-9500-f0b2d1dbeace)
![image](https://github.com/XrunMeta/IssueTracker/assets/14313339/4c327731-be8d-4525-bb3e-99a8d3225b3e)
![image](https://github.com/XrunMeta/IssueTracker/assets/14313339/0f3a3cf7-9464-4f49-ab5f-2a5208c4103a)

**Comment by sungjius** [comment]
as you can see right side ->>> HD button to change image quality. Try it. It seems middle quality set.

**Comment by sungjius** [comment]
<img width="348" alt="image" src="https://github.com/XrunMeta/IssueTracker/assets/81668851/70e02665-c1d9-424a-bcff-313c649a6dd4">

**Comment by trisutrisnowapu** [comment]
Yes I have tried, still problem, very bad. Maybe the problem is in the graphics streamed

**Comment by sungjius** [comment]
gotit. we'd better find other way to checking. Is there no character error or UI problems?

**Comment by trisutrisnowapu** [comment]
UI behaves normally, character skin color black, after some time it got normal. The screen is like covered with that gray plane, I'm not sure but maybe it's like screen space problem

**Comment by sungjius** [comment]
I see. may it caused by network. It's resolution is not perfact. In this case, remote test to find errors by device by device.  Try many devices as we can. If error is raised, check the device and report me. ( In my exp,. it can be raised the same 23 and other 23 not..... We can't meet any devices, but popular ones. this why we try remote testbed.

**Comment by trisutrisnowapu** [comment]
Ok I will test again Mr. Young
