### ISSUE TITLE
NodeServer API Action Range

### ISSUE THREAD

**Issue by bi-brilliant** [XrunMeta/IssueTracker#79]
Useful for coordinating action ranges in creating NodeServer API : 

**Bilal :**
app4000-tokener - app4200-06

**Rian :**
app7000-01 - ap6000-02

**Comment by mfebriann** [comment]
Act still have bug app4000-passwd

**Comment by mfebriann** [comment]
Empty act -> wallet-check

**Comment by mfebriann** [comment]
Act not used on xrun app react native:
- **app7153-01**
- **app7153-02**
- **app7153-03**

**Comment by mfebriann** [comment]
app7000-01 - ap6000-02 it's finish, I will continue with ap6000-03 - app3100-04-check

**Comment by mfebriann** [comment]
> app7000-01 - ap6000-02 it's finish, I will continue with ap6000-03 - app3100-04-check

Function **queryTestExchangingCoins** keep first, can't execute on local. The loading very long and error. Maybe after test on the real server it will work 😃

**Comment by bi-brilliant** [comment]
>
> The **queryTestExchangingCoins** function is temporarily stored, it cannot be run on the local server. The loading process is very long and errors occur. Maybe after testing on the real server it will work 😃

i had same condition if doing some curl to RPC, may need some permissions. Its ok we can next to other func with leave note for that. 

Anyway just inform to you, i will next migrating function from app3100-01 to app4110-01

**Comment by mfebriann** [comment]
> i had same condition if doing some curl to RPC, may need some permissions. Its ok we can next to other func with leave note for that.

Yes, you're right

> Anyway just inform to you, i will next migrating function from app3100-01 to app4110-01

Okey, noted

**Comment by mfebriann** [comment]
> app7000-01 - ap6000-02

@bi-brilliant I have completed this function, I will continue starting from app7410-01 - app4000_account

**Comment by bi-brilliant** [comment]
> > app7000-01 - ap6000-02
> 
> @bi-brilliant I have completed this function, I will continue starting from app7410-01 - app4000_account

okay good, im also finished my range of act above so i will next from login-05-joinAndAccount to ap3105-geth-success

**Comment by mfebriann** [comment]
> @bi-brilliant I have completed this function, I will continue starting from app7420-01 - app4000_account

@bi-brilliant I have completed this function, Tomorrow I will continue starting from nd-1001-xx - app3100-01-pending

**Comment by bi-brilliant** [comment]
>
> @bi-brilliant I have completed this function, Tomorrow I will continue starting from nd-1001-xx - app3100-01-pending
okay nice, then i will mirgate from app4000-01-rev-01 until id1810-region...lets start🔥

**Comment by mfebriann** [comment]
> okay nice, then i will mirgate from app4000-01-rev-01 until id1810-region...lets start🔥

Yeah 🔥 and Bilal. Yesterday I have finished up to app3100-01-pending. I will to continue with start from login-06-joinAndAccount - id4310-email-check

**Comment by bi-brilliant** [comment]
Good...then i will next from check-02-email until digifinex's class

**Comment by mfebriann** [comment]
> Good...then i will next from check-02-email until digifinex's class

I have finished up to id4310-email-check, maybe on Monday I will continue with function deleteTransaction and function sendAuthEmail

**Comment by bi-brilliant** [comment]
Okay, also i will next from authEmail - refreshXRUN
