### ISSUE TITLE
UI changes xrun app (new version)

### ISSUE THREAD

**Issue by sungjius** [XrunMeta/IssueTracker#8]
![image](https://github.com/XrunMeta/IssueTracker/assets/81668851/d1207b02-77cb-4c16-aa96-a20d3645c86b)

When the user gets a coin screen. 

to this ( sample, make it looks similar )

<img width="742" alt="image" src="https://github.com/XrunMeta/IssueTracker/assets/81668851/6f9a7456-8f77-4f17-b9f3-474cdf1d68ba">

**Comment by mfebriann** [comment]
Oke noted, thank you mr young. Btw, can you copy and paste text for korea language?

**Comment by sungjius** [comment]
> Oke noted, thank you mr young. Btw, can you copy and paste text for korea language?

코인잡기성공

**Comment by mfebriann** [comment]
Also text korea language for button mr young

**Comment by sungjius** [comment]
> Also text korea language for button mr young

확인

**Comment by mfebriann** [comment]
Thank you mr young
